app = "fusion-mlops-torchserve"
primary_region = "iad"

[build]
  image = "ghcr.io/seifboukerdenna/fusion-mlops-demo-torchserve:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[services]]
  protocol = "tcp"
  internal_port = 8081

[[services.ports]]
  port = 8081

[[services]]
  protocol = "tcp"
  internal_port = 8082

[[services.ports]]
  port = 8082

[[http_service.checks]]
  grace_period = "30s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/ping"